[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "customer_services_app"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = []


[tool.hatch.build.targets.wheel]
packages = ["app"]

[tool.uv]
add-bounds = "exact"
exclude-newer = "7 days"
package = true


