[project]
name = "customer services App"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = []

[project.scripts]
customer-services = "customer_services:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"


[tool.uv]
add-bounds = "exact"
exclude-newer = "7 days"